#!/usr/bin/env zsh
# Install macOS apps
brew tap homebrew/cask-fonts && brew install --cask font-fira-code &&
brew tap homebrew/cask-versions && brew install --cask firefox-developer-edition --lang=en-US &&
for x in authy zoom iterm2 slack visual-studio-code rectangle mongodb-compass quicklook-csv quicklook-json webpquicklook; do brew install --cask $x; done &&
echo "------------------------\n\nInstalled apps:\n---------------\n" &&
brew list --cask -1
