#!/usr/bin/env zsh
# Install homebrew, then install formulae
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)";
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/`echo $USER`/.zprofile;
eval "$(/opt/homebrew/bin/brew shellenv)";
for x in go gh zsh git antigen zsh-completions exa fasd tree bat; do brew install $x; done &&
brew install fzf && $(brew --prefix)/opt/fzf/install &&
echo "------------------------\n\nInstalled formulae:\n-------------------\n" &&
brew list --formulae -1
