#!/usr/bin/env zsh
# Install homebrew, then install formulae
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" &&
for x in zsh git antigen zsh-completions exa fasd tree bat; do brew install $x; done &&
brew install fzf && $(brew --prefix)/opt/fzf/install

