#!/usr/bin/env zsh

# Update formulae:
brew tap homebrew/cask

# Modify the following command (look it up with `brew cask home <name>`) before running it yourself:
brew cask install background-music bitwarden darktable forklift insomnia jumpcut kap keepingyouawake kindle sketch spotify steam the-unarchiver unison vlc whatsapp
