#!/usr/bin/env zsh
# Install macOS apps
brew tap homebrew/cask-fonts && brew install --cask font-fira-code &&
brew tap homebrew/cask-versions && brew install --cask firefox-developer-edition &&
brew install --cask iterm2 slack visual-studio-code rectangle postman mongodb-compass zoomus quicklook-csv quicklook-json webpquicklook
