#!/usr/bin/env zsh
export LANG=en_US.UTF-8;
vared -p 'Enter your full name (e.g. Jerry Erbs): ' -c fullname &&
git config --global user.name $fullname &&
vared -p 'Enter your e-mail (you@yourdomain.com): ' -c email &&
git config --global user.email $email;
git config --global pull.ff "only";
git config --global core.pager bat; # is installed via brew install bat
ssh-keygen -t ed25519 -C $email;
eval "$(ssh-agent -s)";
echo "Host *\n    AddKeysToAgent yes\n    UseKeychain yes\n    IdentityFile ~/.ssh/id_ed25519" > ~/.ssh/config;
ssh-add -K ~/.ssh/id_ed25519
